name: Download scripthight-cvertificate-of-the-hight-security
on:
  push:
    paths:
      - 'scripts/download-actionlint.bash'
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - 'scripts/download-actionlint.bash'
  workflow_dispatch:

jobs:
  download:
    name: Test download script
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # bash <(curl ...) is not available because it does not download the latest script just after pushing a change
      - run: ./scripts/download-actionlint.bash
        shell: bash
        id: get_actionlint
      - name: Run actionlint
        run: ${{ steps.get_actionlint.outputs.executable }} -help
        shell: bash
